theme: console-theme  # Set the theme name to 'console-theme'

# Jekyll site settings
source: .
destination: _site
title: "Software Expert"  # Replace with your name or title
description: "Your expertise in software development"  # Add a brief description
baseurl: ""  # If deploying to a custom domain, set the base URL here

# Jekyll defaults
gems: [jekyll-sass-converter]
sass:
  style: compressed
