name: Deploying
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  regenerate-docsify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "getting master"
      - uses: actions/checkout@master
      - run: echo "running docsify"
      - uses: tool3/docsify-action@v1.0.3
        with:
          dir: .
          github_token: ${{ secrets.GP_TOKEN }}
      - run: echo "process finished"
